### ISSUE TITLE
Please request an academic account and hide this repository. 

### ISSUE THREAD

**Issue by josephcslater** [ahmedshafee89/CSC6220_DataMining#2]
It is a FERPA violation to list the names of students publicly.

**Comment by akondrahman** [comment]
Thanks. I just sent out a class-wide announcement. 
@mohamed199215 @ahmedshafee89 @sabdelfattah ... please make this repo private and remove names, student IDs etc.

**Comment by ahmedshafee89** [comment]
Dr. Akond,

The names and student IDs have been removed, but the problem in converting
the repo into private is that in private mode, it is allowed only for 3
collaborators at maximum (for github free), this means that I have to
remove two of my friends before converting it into private. So doctor, what
should I do?

**Comment by josephcslater** [comment]
One needs to request an academic account for teaching usage.  I have done it with 6 of my classes in the past. It is best for the professor to request and set up as it won’t look like a student trying to get free stuff.

**Comment by akondrahman** [comment]
@ahmedshafee89 move to CSC GitLab at Tenn. Tech. ... that will reduce a lot of complexity. Contact Jared Jennings if you need access. Add me as a collaborator at arahman@tntech.edu

**Comment by ahmedshafee89** [comment]
Okay doctor.
